### ISSUE TITLE
use design by introspection

### ISSUE THREAD

**Issue by lindt** [fkromer/d-design-patterns#5]
try to be as d idiomatic as possible.

instead of interfaces, try design by introspection.

**Comment by fkromer** [comment]
I read some [DConf slides about Design by Introspection](http://dconf.org/2017/talks/alexandrescu.pdf). But to be honest I do not know how to use DbI instead of interfaces...

**Comment by lindt** [comment]
you would not define an interface. you just would have a struct with method "foo" and then check at compile time if the struct fulfills has such a method.

some hopefully helpful thoughts:
```
struct Foo {
    void execute() {}
}
struct Bar {
    void execute() {}
}

void execute(T)(T item) if (T.hasMember!"execute")  // or if (T.implementsFlyweight)
{
    item.execute(...);
}

// usage
foo.execute(...)
(new Baz()).execute() // compile time error, cause baz does not implement your strategy interface
```

**Comment by ohdatboi** [comment]
We are dealing with common OOP patterns here. There is no need to make everything so complicated, just because we can and it is an "idiomatic D".

> void execute(T)(T item) if (T.hasMember!"execute") 

Now... Try to explain what is metaprogrammingand templates in one comment line. It is impossible. Metaprogramming is hard (maybe hardest technique in programming), and these patterns are for beginners, not for D-pros.

So, it could be used for D-specific patterns (Ranges, for example), not for common patterns.

**Comment by lindt** [comment]
is it more complicated? is it difficult to use?

D design patterns should contain d idiomatic code.

```
#!/usr/bin/env rdmd
/+
dub.json:
{
    "name": "strategy"
}
+/

import std.stdio;

template isStrategy(T) {
    const isStrategy = __traits(hasMember, T, "execute");
}


struct FirstStrategy {
    static assert(isStrategy!FirstStrategy);

    void execute() {
        writeln("first executes");
    }
}

struct SecondStrategy {
    static assert(isStrategy!SecondStrategy);

    void execute() {
        writeln("second executes");
    }
}

void main() {
    auto first = FirstStrategy();
    auto second = SecondStrategy();

    first.execute();
    second.execute();
}
```

it enables to put some patterns into libraries. not sure how much sense does it make for this example.
```
package my_own_awesome_code;

import behaviour.strategy : isStrategy;

struct MyOwnStrategy {
    static assert (isStrategy!MyOwnStrategy);
}

```

**Comment by ohdatboi** [comment]
These examples should be simple, so we don't scare newbies with templates, static asserts.

> D design patterns should contain d idiomatic code.

D-specific patterns - sure, but overcomplicate existing OOP patterns with templates is wrong. They are designed to be used in OOP code, with classes and interfaces.

**Comment by fkromer** [comment]
@lindt @ohdatboi I like idiomatic pattern implementations and consider them valuable because they are harder to learn as they require more language specific experience. The OO implementations are comparably easy to find and easy to port.

I would suggest to put idiomatic pattern implementations into separate directories like e.g. `structural_idiomatic`. If someone would come up with different idiomatic implementations for the same pattern or with implementations which do not compile for all compilers we have to think about another approach again.
